version: "3.8"
services:
  db:
    image: postgres:16
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: isuru
      POSTGRES_PASSWORD: "123456"
      
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  
volumes:
    local_pgdata: